
-- # ASSIGNMENT-4 # --

--USE EMPLOYEE;

SELECT CITY , COUNT(CITY) AS 'NUMBER OF EMPLOYEES' FROM EMP
GROUP BY CITY
ORDER BY 'NUMBER OF EMPLOYEES' DESC;

--------------------

SELECT * FROM EMP
WHERE EMAIL NOT LIKE '%YAHOO%';

--------------------

SELECT DESI, SUM(SALARY) AS 'TOTAL COST', 
	   COUNT(EMPID) AS 'NUMBER OF EMPLOYEES' FROM EMPSAL
GROUP BY DESI
ORDER BY 'TOTAL COST' DESC;
