
-- # ASSIGNMENT-5 # --

--USE EMPLOYEE

SELECT EMP.EMPID, NAME, CITY, DOJ, DEPT, SALARY 
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID=EMPSAL.EMPID
WHERE CITY = 'DELHI';

--------------------

SELECT EMP.EMPID, NAME, ADDR, CITY, PHNO, EMAIL, DOB FROM EMP
LEFT JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE EMPSAL.EMPID IS NULL;
