
-- # ASSIGNMENT-6 # --

--USE EMPLOYEE;

CREATE VIEW EMP_SAL_DETAILS
AS
	SELECT EMP.EMPID, NAME, DOJ, DEPT, DESI, SALARY AS 'BASIC', 
		   (SALARY*0.15) AS 'HRA', (SALARY*0.09) AS 'PF',
		   (SALARY+(SALARY*0.15)+(SALARY*0.09)) AS 'NET', 
		   ((SALARY+(SALARY*0.15)+(SALARY*0.09))-(SALARY*0.09)) AS 'GROSS'
	FROM EMP
	INNER JOIN EMPSAL
	ON EMP.EMPID = EMPSAL.EMPID;

--------------------

CREATE VIEW VIEW_MAN_2K19
AS
	SELECT EMP.EMPID, NAME, DOJ, DESI, DEPT 
	FROM EMP
	INNER JOIN EMPSAL
	ON EMP.EMPID = EMPSAL.EMPID
	WHERE DESI LIKE '%MANAGER%' AND YEAR(DOJ)=2019;

--------------------

SELECT * FROM EMP_SAL_DETAILS;
SELECT * FROM VIEW_MAN_2K19;