

-- # ASSIGNMENT-8 # --

--USE EMPLOYEE;


CREATE FUNCTION CALCULATE (@X INT, @Y INT, @Z CHAR(1))
RETURNS INT
AS
BEGIN
	DECLARE @O AS INT

	IF @Z = '+'
		SET @O = @X+@Y
	ELSE IF @Z = '-'
		SET @O = @X-@Y
	ELSE IF @Z = '*'
		SET @O = @X*@Y
	ELSE IF @Z = '/'
		SET @O = @X/@Y
	ELSE IF @Z = '%'
		SET @O = @X%@Y
	ELSE 
		SET @O = 0

	RETURN @O
END;


SELECT DBO.CALCULATE(10,5,'/') AS 'RESULT';

--------------------

CREATE FUNCTION OFFMAIL (@NAME AS VARCHAR(20), @ID AS CHAR(5))
RETURNS CHAR(13)
AS
BEGIN
	DECLARE @EMAIL AS CHAR(13)

	SET @EMAIL = CONCAT(LEFT(@NAME, 1), 
				        LEFT(RIGHT(@NAME, 
						CHARINDEX(' ' ,@NAME)), 1),
						RIGHT(@ID, 3), '@RCG.COM')

	RETURN @EMAIL
END;


SELECT DBO.OFFMAIL('SURESH KRISHNA','E1066') AS 'OFFICIAL MAIL';

--------------------


CREATE FUNCTION EMP_DEPT (@DEPT CHAR(6))
RETURNS TABLE
AS
	RETURN (SELECT EMP.EMPID, NAME, DESI, DEPT, SALARY
			FROM EMP
			INNER JOIN EMPSAL
			ON EMP.EMPID = EMPSAL.EMPID
			WHERE DEPT= @DEPT);

SELECT * FROM EMP_DEPT('ADMIN');

--------------------

CREATE FUNCTION CURR_BDY()
RETURNS TABLE
AS
	RETURN (SELECT EMP.NAME, DEPT, DESI, CITY
			FROM EMP
			INNER JOIN EMPSAL
			ON EMP.EMPID = EMPSAL.EMPID
			WHERE MONTH(DOB) = MONTH(GETDATE()));

SELECT * FROM CURR_BDY();

--------------------

CREATE FUNCTION SENIOR_EMP()
RETURNS TABLE
AS
	RETURN(SELECT EMP.NAME, DEPT, DOJ
		   FROM EMP
		   INNER JOIN EMPSAL
		   ON EMP.EMPID = EMPSAL.EMPID
		   WHERE DATEDIFF(YY,DOJ,GETDATE())>5);

SELECT * FROM SENIOR_EMP();