
-- # ASSIGNMENT-9 # --

--USE EMPLOYEE;


SELECT EMPID, NAME, CITY FROM EMP
WHERE CITY = 'GURGAON';

--USING SUBQUERY

SELECT EMPID, NAME, CITY FROM EMP
WHERE CITY IN (SELECT CITY FROM EMP WHERE CITY = 'GURGAON');

--------------------

SELECT EMP.EMPID, NAME, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DESI = 'MANAGER';

--USING SUBQUERY

SELECT EMP.EMPID, NAME, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DESI IN (SELECT DESI FROM EMPSAL WHERE DESI = 'MANAGER');

--------------------

UPDATE EMPSAL SET SALARY = (SALARY - (SALARY*0.1))
WHERE EMPID IN (SELECT EMPID FROM EMP WHERE CITY = 'DELHI');

--------------------

SELECT EMP.EMPID, NAME, CITY, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL 
ON EMP.EMPID = EMPSAL.EMPID
WHERE DEPT IN (SELECT DEPT FROM EMPSAL 
			   WHERE EMPID IN (SELECT EMPID FROM EMP 
							   WHERE NAME LIKE 'DAVID' 
							   OR NAME LIKE 'RAMESH GUPTA'));

--------------------

-- CREATING TRAINING TABLE
	--CREATE TABLE TRAINING
	--(EMPID VARCHAR(5),
	--NAME VARCHAR(20),
	--DEPT CHAR(6));


INSERT INTO TRAINING (EMPID, NAME, DEPT)
(SELECT EMP.EMPID, NAME, DEPT
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DEPT = 'OPS');	

SELECT * FROM TRAINING;

--------------------

DELETE TRAINING
WHERE EMPID IN (SELECT EMPID FROM EMPSAL WHERE DESI = 'DIRECTOR')

SELECT * FROM TRAINING;

--------------------

--QUESTION UNCLEAR--
SELECT * FROM EMPSAL
WHERE EXISTS (SELECT SALARY FROM EMPSAL 
			  WHERE SALARY > 200000);
--OTHER POSSIBLE QUERY
SELECT * FROM EMPSAL
WHERE DEPT IN(SELECT DEPT FROM EMPSAL
			  WHERE SALARY > 200000);